-- Apply after 0001 + 0002. Photos live in the Next app at /images/people/{id}.jpg

insert into public.house_members (id, first_name, age, city_area, photo_path, intention, traits, visibility, verified, path, about, why, difference, moment_hint) values
('maya','Maya',32,'West of the river','/images/people/maya.jpg','A long-term relationship','{Measured,Warm,Private}','private',true,'woman-seeking-man','I work in architecture. I like evenings that do not ask me to perform.','','','quiet'),
('elena','Elena',31,'The old quarter','/images/people/elena.jpg','A life partnership','{Precise,Dry humour,Loyal}','public',true,'woman-seeking-man','I restore paintings.','She treats attention as a scarce material.','She keeps a quieter social life than you sometimes want.','quiet'),
('nora','Nora',34,'Near the gardens','/images/people/nora.jpg','A long-term relationship','{Curious,Warm,Independent}','public',true,'woman-seeking-man','I edit documentary films.','She is interested in ordinary Tuesdays.','She is away more often than a settled week easily holds.','travel'),
('iris','Iris',29,'East ridge','/images/people/iris.jpg','Marriage','{Direct,Kind,Family-minded}','public',true,'woman-seeking-man','I run a small ceramics studio.','She is ready to build something lasting.','She is closer to wanting children than you have said out loud.','food'),
('hana','Hana',36,'By the water','/images/people/hana.jpg','A life partnership','{Calm,Exact,Witty}','public',true,'woman-seeking-man','I practise law and keep Fridays empty.','She protects time the way you do.','She is less spontaneous than your better weekends.','quiet'),
('lucia','Lucia',33,'The old quarter','/images/people/lucia.jpg','A long-term relationship','{Musical,Warm,Considered}','public',true,'woman-seeking-man','I teach piano.','You share a preference for atmosphere over spectacle.','She is more at ease in a group than you usually are.','playful'),
('claire','Claire',38,'West of the river','/images/people/claire.jpg','A life partnership','{Grounded,Private,Generous}','public',true,'woman-seeking-man','I design gardens.','She makes things slowly.','Her days are quieter than your present week allows.','quiet'),
('amara','Amara',30,'Near the gardens','/images/people/amara.jpg','A long-term relationship','{Thoughtful,Playful,Steady}','public',true,'woman-seeking-man','I write for a journal and keep a serious kitchen.','She has humour that does not need an audience.','She is more social at a table than on a dance floor.','food'),
('sienna','Sienna',35,'East ridge','/images/people/sienna.jpg','Marriage','{Intentional,Warm,Clear}','public',true,'woman-seeking-man','I work in publishing.','She takes language seriously.','She would like to be married sooner than a long courtship prefers.','quiet'),
('viola','Viola',28,'By the water','/images/people/viola.jpg','A long-term relationship','{Curious,Independent,Kind}','public',true,'woman-seeking-man','I work in conservation.','She can travel without turning a person into a postcard.','She needs more solitude than a full social week easily gives.','travel'),
('priya','Priya',37,'West of the river','/images/people/priya.jpg','A life partnership','{Measured,Witty,Loyal}','public',true,'woman-seeking-man','I run a research lab.','She wants fewer people, known well.','Her work weeks are longer than a leisurely courtship assumes.','food'),
('wren','Wren',32,'The old quarter','/images/people/wren.jpg','A long-term relationship','{Private,Warm,Exact}','private',true,'woman-seeking-man','Private profile.','','','quiet'),
('julian','Julian',33,'West of the river','/images/people/julian.jpg','A life partnership','{Intentional,Warm,Curious}','public',true,'man-seeking-woman','I edit books. I cook on Sundays.','You both want a quieter life.','He prefers quieter evenings than you sometimes do.','quiet'),
('marcus','Marcus',36,'East ridge','/images/people/marcus.jpg','Marriage','{Steady,Dry humour,Family-minded}','public',true,'man-seeking-woman','I run a small workshop.','Shared wish for a household.','He is ready for children sooner than you have said.','food'),
('daniel','Daniel',34,'Near the gardens','/images/people/daniel.jpg','A long-term relationship','{Considered,Musical,Loyal}','public',true,'man-seeking-woman','I teach, and I keep Fridays.','You both protect your weekends.','He is more social in groups than you are.','playful'),
('thomas','Thomas',38,'By the water','/images/people/thomas.jpg','A life partnership','{Calm,Exact,Kind}','public',true,'man-seeking-woman','I design gardens.','A shared preference for making things slowly.','He lives more quietly than your present week allows.','quiet'),
('owen','Owen',31,'The old quarter','/images/people/owen.jpg','A long-term relationship','{Curious,Grounded,Warm}','public',true,'man-seeking-woman','I cook for a living.','He understands food as care.','His work nights run later than a quiet household prefers.','food'),
('felix','Felix',39,'West of the river','/images/people/felix.jpg','A life partnership','{Measured,Witty,Loyal}','public',true,'man-seeking-woman','I practise architecture.','He notices rooms the way you do.','He is slower to decide than your patience sometimes likes.','quiet'),
('adrian','Adrian',35,'East ridge','/images/people/adrian.jpg','Marriage','{Direct,Generous,Steady}','public',true,'man-seeking-woman','I run a family firm.','He is clear about wanting a life.','He is more conventional about weekends than you are.','food'),
('nico','Nico',29,'By the water','/images/people/nico.jpg','A long-term relationship','{Playful,Kind,Independent}','public',true,'man-seeking-woman','I photograph still lives.','He has humour without cruelty.','He is away more than a settled February easily holds.','travel'),
('rafael','Rafael',37,'Near the gardens','/images/people/rafael.jpg','A life partnership','{Musical,Warm,Considered}','public',true,'man-seeking-woman','I conduct.','He understands atmosphere.','Performance weeks make him less available.','playful'),
('leo','Leo',32,'The old quarter','/images/people/leo.jpg','A long-term relationship','{Curious,Calm,Honest}','public',true,'man-seeking-woman','I write history.','He is serious about ordinary days.','His social energy arrives in bursts.','quiet'),
('james','James',35,'East ridge','/images/people/james.jpg','Marriage','{Direct,Generous,Grounded}','private',true,'man-seeking-woman','Private profile.','','','food')
on conflict (id) do nothing;
