export type Person = {
  id: string;
  firstName: string;
  age: number;
  city: string;
  photo: string;
  intention: string;
  traits: string[];
  visibility: "public" | "private";
  verified: boolean;
  path: "man-seeking-woman" | "woman-seeking-man";
  about: string;
  why?: string;
  difference?: string;
  momentHint?: "travel" | "food" | "quiet" | "playful";
};

const house: Person[] = [
  {
    id: "maya",
    firstName: "Maya",
    age: 32,
    city: "West of the river",
    photo: "/images/people/maya.jpg",
    intention: "A long-term relationship",
    traits: ["Measured", "Warm", "Private"],
    visibility: "private",
    verified: true,
    path: "woman-seeking-man",
    about: "I work in architecture. I like evenings that do not ask me to perform. Sundays are for walking and cooking something that takes too long.",
    momentHint: "quiet",
  },
  {
    id: "elena",
    firstName: "Elena",
    age: 31,
    city: "The old quarter",
    photo: "/images/people/elena.jpg",
    intention: "A life partnership",
    traits: ["Precise", "Dry humour", "Loyal"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I restore paintings. I am looking for a companion who can sit in a room without filling it.",
    why: "She treats attention as a scarce material. You both dislike haste, and you both notice how a room is lit.",
    difference: "She keeps a quieter social life than you sometimes want.",
    momentHint: "quiet",
  },
  {
    id: "nora",
    firstName: "Nora",
    age: 34,
    city: "Near the gardens",
    photo: "/images/people/nora.jpg",
    intention: "A long-term relationship",
    traits: ["Curious", "Warm", "Independent"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I edit documentary films. I travel when the work allows, and I come home on purpose.",
    why: "She is interested in how people spend an ordinary Tuesday — not in a performance of adventure.",
    difference: "She is away more often than a settled week easily holds.",
    momentHint: "travel",
  },
  {
    id: "iris",
    firstName: "Iris",
    age: 29,
    city: "East ridge",
    photo: "/images/people/iris.jpg",
    intention: "Marriage",
    traits: ["Direct", "Kind", "Family-minded"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I run a small ceramics studio. I want a household, not an audience.",
    why: "She is ready to build something lasting, and she is unusually honest about the unglamorous parts.",
    difference: "She is closer to wanting children than you have said out loud.",
    momentHint: "food",
  },
  {
    id: "hana",
    firstName: "Hana",
    age: 36,
    city: "By the water",
    photo: "/images/people/hana.jpg",
    intention: "A life partnership",
    traits: ["Calm", "Exact", "Witty"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I practise law and keep Fridays empty. I would rather know one person well than collect evenings.",
    why: "She protects time the way you do. Conversation, for her, is a craft.",
    difference: "She is less spontaneous than your better weekends.",
    momentHint: "quiet",
  },
  {
    id: "lucia",
    firstName: "Lucia",
    age: 33,
    city: "The old quarter",
    photo: "/images/people/lucia.jpg",
    intention: "A long-term relationship",
    traits: ["Musical", "Warm", "Considered"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I teach piano. Evenings are for cooking or a room with live music and no obligation to dance.",
    why: "You share a preference for atmosphere over spectacle, and for people who listen to the end of a sentence.",
    difference: "She is more at ease in a group than you usually are.",
    momentHint: "playful",
  },
  {
    id: "claire",
    firstName: "Claire",
    age: 38,
    city: "West of the river",
    photo: "/images/people/claire.jpg",
    intention: "A life partnership",
    traits: ["Grounded", "Private", "Generous"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I design gardens. I am looking for a companion to walk with, not a project to improve.",
    why: "She makes things slowly. She will not rush a first evening, and she will not pretend to.",
    difference: "Her days are quieter than your present week allows.",
    momentHint: "quiet",
  },
  {
    id: "amara",
    firstName: "Amara",
    age: 30,
    city: "Near the gardens",
    photo: "/images/people/amara.jpg",
    intention: "A long-term relationship",
    traits: ["Thoughtful", "Playful", "Steady"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I write for a journal and keep a serious kitchen. I like people who can be funny without becoming cheap.",
    why: "She has humour that does not need an audience. Food, for her, is how a day becomes an evening.",
    difference: "She is more social at a table than on a dance floor — or the reverse of what you expect.",
    momentHint: "food",
  },
  {
    id: "sienna",
    firstName: "Sienna",
    age: 35,
    city: "East ridge",
    photo: "/images/people/sienna.jpg",
    intention: "Marriage",
    traits: ["Intentional", "Warm", "Clear"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I work in publishing. I want a partnership that can survive a dull February.",
    why: "She takes language seriously, and she is not interested in being chosen for a photograph.",
    difference: "She would like to be married sooner than a long, careful courtship prefers.",
    momentHint: "quiet",
  },
  {
    id: "viola",
    firstName: "Viola",
    age: 28,
    city: "By the water",
    photo: "/images/people/viola.jpg",
    intention: "A long-term relationship",
    traits: ["Curious", "Independent", "Kind"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I work in conservation. I take one proper trip a year and otherwise stay put.",
    why: "She is looking for someone who can travel without turning the other person into a postcard.",
    difference: "She needs more solitude than a full social week easily gives.",
    momentHint: "travel",
  },
  {
    id: "priya",
    firstName: "Priya",
    age: 37,
    city: "West of the river",
    photo: "/images/people/priya.jpg",
    intention: "A life partnership",
    traits: ["Measured", "Witty", "Loyal"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I run a research lab. I cook on Sundays and I do not date as a hobby.",
    why: "She wants fewer people, known well. She will not perform enthusiasm she does not feel.",
    difference: "Her work weeks are longer than a leisurely courtship assumes.",
    momentHint: "food",
  },
  {
    id: "wren",
    firstName: "Wren",
    age: 32,
    city: "The old quarter",
    photo: "/images/people/wren.jpg",
    intention: "A long-term relationship",
    traits: ["Private", "Warm", "Exact"],
    visibility: "private",
    verified: true,
    path: "woman-seeking-man",
    about: "Private profile. Visible to a matchmaker, not to Available.",
    momentHint: "quiet",
  },
  {
    id: "julian",
    firstName: "Julian",
    age: 33,
    city: "West of the river",
    photo: "/images/people/julian.jpg",
    intention: "A life partnership",
    traits: ["Intentional", "Warm", "Curious"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I edit books. I cook on Sundays. I would rather know one person well.",
    why: "You both want a quieter life, and you both take language seriously.",
    difference: "He prefers quieter evenings than you sometimes do.",
    momentHint: "quiet",
  },
  {
    id: "marcus",
    firstName: "Marcus",
    age: 36,
    city: "East ridge",
    photo: "/images/people/marcus.jpg",
    intention: "Marriage",
    traits: ["Steady", "Dry humour", "Family-minded"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I run a small workshop. I am looking for someone to build a household with.",
    why: "Shared wish for a household, and a dislike of spectacle.",
    difference: "He is ready for children sooner than you have said.",
    momentHint: "food",
  },
  {
    id: "daniel",
    firstName: "Daniel",
    age: 34,
    city: "Near the gardens",
    photo: "/images/people/daniel.jpg",
    intention: "A long-term relationship",
    traits: ["Considered", "Musical", "Loyal"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I teach, and I keep Fridays for no one but the people I love.",
    why: "You both protect your weekends, and you both dislike haste.",
    difference: "He is more social in groups than you are.",
    momentHint: "playful",
  },
  {
    id: "thomas",
    firstName: "Thomas",
    age: 38,
    city: "By the water",
    photo: "/images/people/thomas.jpg",
    intention: "A life partnership",
    traits: ["Calm", "Exact", "Kind"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I design gardens. I am looking for a companion, not an audience.",
    why: "A shared preference for making things slowly.",
    difference: "He lives more quietly than your present week allows.",
    momentHint: "quiet",
  },
  {
    id: "owen",
    firstName: "Owen",
    age: 31,
    city: "The old quarter",
    photo: "/images/people/owen.jpg",
    intention: "A long-term relationship",
    traits: ["Curious", "Grounded", "Warm"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I cook for a living and refuse to turn dinner into a performance. I want someone to come home to.",
    why: "He understands food as care, not as display. The evenings he wants look like yours.",
    difference: "His work nights run later than a quiet household prefers.",
    momentHint: "food",
  },
  {
    id: "felix",
    firstName: "Felix",
    age: 39,
    city: "West of the river",
    photo: "/images/people/felix.jpg",
    intention: "A life partnership",
    traits: ["Measured", "Witty", "Loyal"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I practise architecture. I walk most evenings. I am not looking for a project.",
    why: "He notices rooms the way you do. He will not fill a silence just to own it.",
    difference: "He is slower to decide than your patience sometimes likes.",
    momentHint: "quiet",
  },
  {
    id: "adrian",
    firstName: "Adrian",
    age: 35,
    city: "East ridge",
    photo: "/images/people/adrian.jpg",
    intention: "Marriage",
    traits: ["Direct", "Generous", "Steady"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I run a family firm and I am ready for a household. I do not date as entertainment.",
    why: "He is clear about wanting a life, not a season. He will not waste a careful woman’s time.",
    difference: "He is more conventional about weekends than you are.",
    momentHint: "food",
  },
  {
    id: "nico",
    firstName: "Nico",
    age: 29,
    city: "By the water",
    photo: "/images/people/nico.jpg",
    intention: "A long-term relationship",
    traits: ["Playful", "Kind", "Independent"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I photograph still lives and travel when a commission appears. I come home on purpose.",
    why: "He has humour without cruelty, and he is looking for someone who can leave a city and return.",
    difference: "He is away more than a settled February easily holds.",
    momentHint: "travel",
  },
  {
    id: "rafael",
    firstName: "Rafael",
    age: 37,
    city: "Near the gardens",
    photo: "/images/people/rafael.jpg",
    intention: "A life partnership",
    traits: ["Musical", "Warm", "Considered"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I conduct. I keep one evening a week with no score on the stand.",
    why: "He understands atmosphere. He is not interested in being impressive at dinner.",
    difference: "Performance weeks make him less available than a new connection likes.",
    momentHint: "playful",
  },
  {
    id: "leo",
    firstName: "Leo",
    age: 32,
    city: "The old quarter",
    photo: "/images/people/leo.jpg",
    intention: "A long-term relationship",
    traits: ["Curious", "Calm", "Honest"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I write history and cook badly with enthusiasm. I want a person, not a calendar of dates.",
    why: "He is serious about ordinary days. He will tell you the unflattering thing early.",
    difference: "His social energy arrives in bursts, then he disappears into work.",
    momentHint: "quiet",
  },
  {
    id: "james",
    firstName: "James",
    age: 35,
    city: "East ridge",
    photo: "/images/people/james.jpg",
    intention: "Marriage",
    traits: ["Direct", "Generous", "Grounded"],
    visibility: "private",
    verified: true,
    path: "man-seeking-woman",
    about: "Private profile. Visible to a matchmaker, not to Available.",
    momentHint: "food",
  },
  {
    id: "sage",
    firstName: "Sage",
    age: 31,
    city: "Near the gardens",
    photo: "/images/people/sage.jpg",
    intention: "A long-term relationship",
    traits: ["Quiet", "Funny", "Loyal"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I design type. I want someone who notices the space between things.",
    why: "She is precise without being cold. Evenings, for her, are for one conversation done properly.",
    difference: "She leaves parties earlier than you might.",
    momentHint: "quiet",
  },
  {
    id: "lila",
    firstName: "Lila",
    age: 27,
    city: "The old quarter",
    photo: "/images/people/lila.jpg",
    intention: "A life partnership",
    traits: ["Warm", "Curious", "Steady"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I work in archives. I like people who can be still.",
    why: "She is looking for a life that can hold both a trip and a Tuesday.",
    difference: "She is younger in years than in how she keeps a household.",
    momentHint: "travel",
  },
  {
    id: "esme",
    firstName: "Esme",
    age: 34,
    city: "West of the river",
    photo: "/images/people/esme.jpg",
    intention: "Marriage",
    traits: ["Direct", "Kind", "Musical"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I run a small restaurant. I am ready for a partner, not a guest list.",
    why: "Food is how she cares. She will not perform a first date she does not mean.",
    difference: "Service nights make her later than a quiet courtship prefers.",
    momentHint: "food",
  },
  {
    id: "flora",
    firstName: "Flora",
    age: 36,
    city: "By the water",
    photo: "/images/people/flora.jpg",
    intention: "A long-term relationship",
    traits: ["Calm", "Private", "Witty"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I translate poetry. I want fewer people and better evenings.",
    why: "She listens to the end of a sentence. She will not fill a silence to own it.",
    difference: "She needs more solitude than a busy week easily gives.",
    momentHint: "quiet",
  },
  {
    id: "nia",
    firstName: "Nia",
    age: 30,
    city: "East ridge",
    photo: "/images/people/nia.jpg",
    intention: "A life partnership",
    traits: ["Playful", "Grounded", "Clear"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I practise medicine and keep Sundays empty on purpose.",
    why: "She is serious about ordinary care. Humour arrives when she trusts the room.",
    difference: "On-call weeks interrupt a carefully planned Friday.",
    momentHint: "playful",
  },
  {
    id: "orla",
    firstName: "Orla",
    age: 39,
    city: "Near the gardens",
    photo: "/images/people/orla.jpg",
    intention: "A long-term relationship",
    traits: ["Measured", "Warm", "Independent"],
    visibility: "public",
    verified: true,
    path: "woman-seeking-man",
    about: "I restore furniture. I am looking for a companion who can sit without performing.",
    why: "She makes things slowly and expects the same of a first introduction.",
    difference: "She is less interested in travel than your better years have been.",
    momentHint: "food",
  },
  {
    id: "hugo",
    firstName: "Hugo",
    age: 34,
    city: "West of the river",
    photo: "/images/people/hugo.jpg",
    intention: "A life partnership",
    traits: ["Quiet", "Exact", "Kind"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I bind books. I want a person to come home to, not a season of dates.",
    why: "He treats time as a material. He will not rush a first evening.",
    difference: "He is slower in a group than you sometimes are.",
    momentHint: "quiet",
  },
  {
    id: "caleb",
    firstName: "Caleb",
    age: 31,
    city: "The old quarter",
    photo: "/images/people/caleb.jpg",
    intention: "A long-term relationship",
    traits: ["Warm", "Direct", "Curious"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I teach design. I cook on Sundays and refuse to turn dinner into a show.",
    why: "He is looking for someone who can be funny without becoming cheap.",
    difference: "He is more social at a table than after ten.",
    momentHint: "food",
  },
  {
    id: "evan",
    firstName: "Evan",
    age: 37,
    city: "East ridge",
    photo: "/images/people/evan.jpg",
    intention: "Marriage",
    traits: ["Steady", "Witty", "Loyal"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I practise family law. I am ready for a household.",
    why: "He is clear about wanting a life, not an inbox. He will not waste a careful woman’s time.",
    difference: "He is more conventional about weekends than you are.",
    momentHint: "quiet",
  },
  {
    id: "miles",
    firstName: "Miles",
    age: 29,
    city: "By the water",
    photo: "/images/people/miles.jpg",
    intention: "A long-term relationship",
    traits: ["Musical", "Playful", "Kind"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I write songs and keep one evening a week with no plan.",
    why: "He understands atmosphere. He is not interested in being impressive at dinner.",
    difference: "Touring weeks make him less available than a new connection likes.",
    momentHint: "playful",
  },
  {
    id: "asher",
    firstName: "Asher",
    age: 40,
    city: "Near the gardens",
    photo: "/images/people/asher.jpg",
    intention: "A life partnership",
    traits: ["Calm", "Generous", "Private"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I keep a small vineyard outside the city. I come in on Thursdays.",
    why: "He wants fewer people, known well. The life he is offering is slower on purpose.",
    difference: "The countryside is more of his week than yours is now.",
    momentHint: "food",
  },
  {
    id: "romy",
    firstName: "Romy",
    age: 33,
    city: "The old quarter",
    photo: "/images/people/romy.jpg",
    intention: "A long-term relationship",
    traits: ["Curious", "Warm", "Honest"],
    visibility: "public",
    verified: true,
    path: "man-seeking-woman",
    about: "I photograph interiors. I want someone who notices how a room is lit.",
    why: "He will tell you the unflattering thing early. He is serious about ordinary days.",
    difference: "Work travel arrives in bursts, then he disappears into the studio.",
    momentHint: "travel",
  },
];

const extraWomen: Person[] = (
  [
    ["ada", "Ada", 28, "The old quarter", "A long-term relationship", ["Warm", "Exact", "Private"], "I keep a small archive and a serious kitchen.", "She treats attention as something you spend carefully.", "She is younger than the life she is already keeping.", "quiet"],
    ["belle", "Belle", 33, "Near the gardens", "A life partnership", ["Calm", "Witty", "Loyal"], "I arrange flowers for private houses. Evenings are for one table.", "She makes rooms feel finished without filling them.", "Her work weeks bloom, then go completely quiet.", "food"],
    ["camille", "Camille", 31, "West of the river", "A long-term relationship", ["Musical", "Warm", "Independent"], "I play violin and refuse to turn a first evening into a recital.", "She understands atmosphere. Humour arrives when she trusts you.", "Practice nights run later than a quiet courtship prefers.", "playful"],
    ["dahlia", "Dahlia", 36, "By the water", "Marriage", ["Measured", "Kind", "Clear"], "I work with wine. I am ready for a partner, not a season of guests.", "She is serious about ordinary Tuesdays and a household.", "She would like to be married sooner than a long courtship prefers.", "food"],
    ["eve", "Eve", 29, "East ridge", "A long-term relationship", ["Curious", "Private", "Playful"], "I photograph still rooms. I want someone who can sit without performing.", "She notices light the way you notice people.", "She needs more solitude than a full social week easily gives.", "quiet"],
    ["freya", "Freya", 34, "The old quarter", "A life partnership", ["Precise", "Warm", "Steady"], "I practise architecture. Sundays are for walking and something that takes too long.", "She treats time as a material. She will not rush a first evening.", "She is slower to decide than impatience likes.", "quiet"],
    ["gina", "Gina", 32, "Near the gardens", "A long-term relationship", ["Grounded", "Funny", "Loyal"], "I fire ceramics and keep Fridays empty on purpose.", "She is looking for a life that can hold both a trip and a Tuesday.", "She leaves parties earlier than you might.", "food"],
    ["holly", "Holly", 27, "West of the river", "A long-term relationship", ["Curious", "Kind", "Honest"], "I work in a bookshop. I like people who finish their sentences.", "She is younger in years than in how she keeps a week.", "She is less travelled than your better years have been.", "quiet"],
    ["ivy", "Ivy", 35, "By the water", "A life partnership", ["Calm", "Generous", "Private"], "I design gardens. I want fewer people, known well.", "She makes things slowly and expects the same of an introduction.", "Her days are quieter than a busy February allows.", "travel"],
    ["june", "June", 30, "East ridge", "A long-term relationship", ["Warm", "Direct", "Playful"], "I bake for a small hotel. Care, for me, arrives as breakfast.", "She will not perform a first date she does not mean.", "Service mornings make her earlier than a late household prefers.", "food"],
    ["kate", "Kate", 38, "West of the river", "Marriage", ["Measured", "Witty", "Family-minded"], "I practise law and keep one evening a week with no plan.", "She is clear about wanting a life, not an inbox.", "She is more conventional about weekends than you are.", "quiet"],
    ["lena", "Lena", 31, "The old quarter", "A long-term relationship", ["Musical", "Curious", "Warm"], "I teach contemporary dance. I want a companion who can be still afterwards.", "She has humour that does not need an audience.", "She is more at ease in a group than a private man sometimes is.", "playful"],
    ["mira", "Mira", 33, "Near the gardens", "A life partnership", ["Exact", "Kind", "Independent"], "I run a research lab. I protect Sundays the way other people protect a reputation.", "She wants fewer people, known well. She will not waste a careful evening.", "Work weeks are longer than a leisurely courtship assumes.", "quiet"],
    ["noelle", "Noelle", 28, "By the water", "A long-term relationship", ["Warm", "Private", "Curious"], "I illustrate children's books and keep a serious kitchen.", "She is looking for someone who can be funny without becoming cheap.", "She is quieter in a room than a first photograph suggests.", "food"],
    ["ophelia", "Ophelia", 37, "East ridge", "A life partnership", ["Measured", "Loyal", "Clear"], "I work in the theatre, then come home and refuse to perform.", "She understands atmosphere and will not fill a silence to own it.", "Opening weeks make her less available than a new connection likes.", "playful"],
    ["pearl", "Pearl", 34, "West of the river", "A long-term relationship", ["Calm", "Witty", "Steady"], "I weave textiles. I want evenings that do not ask me to be impressive.", "She treats attention as a scarce material.", "She needs more solitude than a full calendar easily gives.", "quiet"],
    ["quinn", "Quinn", 29, "The old quarter", "A long-term relationship", ["Direct", "Warm", "Independent"], "I write for a journal. I am not looking for a performance, or a race.", "She will tell you the unflattering thing early.", "She is away more often than a settled week easily holds.", "travel"],
    ["rosa", "Rosa", 36, "Near the gardens", "Marriage", ["Generous", "Grounded", "Kind"], "I keep a small olive farm and come into the city on Thursdays.", "She wants a household. Food is how she cares.", "The countryside is more of her week than yours is now.", "food"],
    ["selene", "Selene", 32, "By the water", "A life partnership", ["Quiet", "Curious", "Loyal"], "I work with light — film, then a dark kitchen.", "She listens to the end of a sentence.", "She leaves the city more often than a new introduction prefers.", "quiet"],
    ["thea", "Thea", 39, "East ridge", "A long-term relationship", ["Measured", "Warm", "Private"], "I restore antiques. I am looking for a companion who can sit without filling the room.", "She makes things slowly. She expects the same of a first evening.", "She is less interested in travel than your better years have been.", "quiet"],
    ["uma", "Uma", 30, "West of the river", "A long-term relationship", ["Calm", "Playful", "Clear"], "I practise physiotherapy and keep Sundays empty on purpose.", "She is serious about ordinary care. Humour arrives when she trusts the room.", "On-call weeks interrupt a carefully planned Friday.", "playful"],
    ["vera", "Vera", 35, "The old quarter", "A life partnership", ["Precise", "Kind", "Independent"], "I translate. I want someone who notices the space between things.", "She is precise without being cold.", "She needs more quiet than a busy week easily gives.", "quiet"],
    ["willa", "Willa", 27, "Near the gardens", "A long-term relationship", ["Curious", "Warm", "Honest"], "I edit documentary films. I like people who can be still.", "She is interested in ordinary Tuesdays, not a highlight reel.", "She is away more than a settled February easily holds.", "travel"],
    ["xia", "Xia", 31, "By the water", "A life partnership", ["Quiet", "Witty", "Loyal"], "I keep a tea house. Evenings, for me, are for one conversation done properly.", "She treats hospitality as a private act.", "She closes later than a quiet courtship prefers.", "food"],
    ["yara", "Yara", 34, "East ridge", "A long-term relationship", ["Measured", "Warm", "Curious"], "I design interiors. I want a person to come home to, not a season of dates.", "She notices rooms the way you notice people.", "She is slower in a group than you sometimes are.", "quiet"],
    ["zoe", "Zoe", 28, "West of the river", "A long-term relationship", ["Playful", "Kind", "Independent"], "I sail when the work is finished. I want someone who can travel without turning a person into a postcard.", "She can be light without becoming cheap.", "Summer weeks take her farther than a new connection likes.", "travel"],
    ["anouk", "Anouk", 36, "The old quarter", "A life partnership", ["Calm", "Exact", "Generous"], "I sculpt. I am ready for a partner who can sit in a room without filling it.", "She wants fewer people, known well.", "Studio weeks make her less available than a careful Friday assumes.", "quiet"],
    ["bridget", "Bridget", 33, "Near the gardens", "A long-term relationship", ["Grounded", "Warm", "Private"], "I keep horses outside the city. I come in when the week asks.", "The life she is offering is slower on purpose.", "The countryside is more of her week than a city man expects.", "travel"],
    ["cecile", "Cecile", 40, "By the water", "Marriage", ["Measured", "Musical", "Loyal"], "I teach piano. I am ready for a household, not a guest list.", "She understands atmosphere. She will not waste a careful evening.", "She is more conventional about weekends than you are.", "playful"],
    ["diana", "Diana", 29, "East ridge", "A long-term relationship", ["Curious", "Kind", "Steady"], "I work in conservation. I like evenings that do not ask me to perform.", "She can travel without turning the other person into scenery.", "She needs more solitude than a full social week easily gives.", "travel"],
    ["eloise", "Eloise", 32, "West of the river", "A life partnership", ["Warm", "Direct", "Clear"], "I run a small hotel kitchen. I want a companion, not an audience.", "Food is how she cares. She will not perform a first date she does not mean.", "Service nights make her later than a quiet household prefers.", "food"],
    ["faye", "Faye", 35, "The old quarter", "A long-term relationship", ["Intentional", "Witty", "Private"], "I work in publishing. I take language seriously and people slowly.", "She is looking for someone who can speak plainly.", "She would rather write than stay out past ten.", "quiet"],
  ] as const
).map(([id, firstName, age, city, intention, traits, about, why, difference, momentHint]) => ({
  id,
  firstName,
  age,
  city,
  photo: `/images/people/${id}.jpg`,
  intention,
  traits: [...traits],
  visibility: "public" as const,
  verified: true,
  path: "woman-seeking-man" as const,
  about,
  why,
  difference,
  momentHint,
}));

export const people: Person[] = [...house, ...extraWomen].map((person) => {
  if (person.id === "quinn") return { ...person, photo: "/images/people/quinn-w.jpg" };
  if (person.id === "thea") return { ...person, photo: "/images/people/thea-w.jpg" };
  return person;
});

export function personById(id: string) {
  return people.find((person) => person.id === id);
}

export function availableFor(viewer: Person | undefined) {
  if (!viewer) return [];
  const seeking = viewer.path === "woman-seeking-man" ? "man-seeking-woman" : "woman-seeking-man";
  return people.filter((person) => person.id !== viewer.id && person.visibility === "public" && person.path === seeking);
}

const onlineIds = new Set([
  "julian",
  "daniel",
  "owen",
  "nico",
  "miles",
  "hugo",
  "elena",
  "lucia",
  "amara",
  "sage",
  "nia",
  "flora",
  "esme",
  "ada",
  "camille",
  "freya",
  "ivy",
  "lena",
  "mira",
  "rosa",
  "selene",
  "yara",
  "zoe",
  "anouk",
  "eloise",
]);

export function isOnline(id: string) {
  return onlineIds.has(id);
}

export function memberFromEmail(email: string) {
  const value = email.toLowerCase();
  const hit = people.find((person) => value.includes(person.id));
  if (hit) return hit.id;
  return "julian";
}
